### ISSUE TITLE
Authentication: WordPress.com Connection

### ISSUE THREAD

**Issue by findingsimple** [woocommerce/google-listings-and-ads#1]
**User story:**

As a merchant
I want to connect my store to WordPress.com
So that I can use WooCommerce products that need to securely communicate with WordPress.com infrastructure/services.

**Description:**

We need to make requests to WordPress.com infrastructure/services (api.woo) to facilitate:
* Google OAuth / Authentication
* Proxying requests to the Google Ads api (so that we inject our developer token)

We can take a similar approach to WCPay and use the [Jetpack connection module](https://github.com/Automattic/jetpack/tree/master/packages/connection) to allow Merchants to connect a WordPress.com account and obtain tokens that can be used to communicate with api.woo services.

**Screenshots**

![Screen Shot 2020-11-03 at 3 44 09 pm](https://user-images.githubusercontent.com/355014/97951907-95a3eb80-1deb-11eb-93a2-835dc7c25972.png)

Clicking connect will begin the WordPress.com Jetpack connection flow and once completed they will be redirected back to this page/screen

![Screen Shot 2020-11-03 at 4 11 12 pm](https://user-images.githubusercontent.com/355014/97953083-6d1df080-1def-11eb-9525-8ad01575a242.png)

A snackbar notice will be displayed to provide feedback to the merchant on success/failure

![Screen Shot 2020-11-03 at 4 13 23 pm](https://user-images.githubusercontent.com/355014/97953163-976fae00-1def-11eb-8d25-2f98a89a1bbe.png)

**Technical:**
* Button component
* Snackbar notice component

**Acceptance criteria:**

* [x] Merchant can choose which account to connect with
* [x] Merchant can choose to disconnect the WordPress.com account
* [x] Button color updates to reflect admin profile color scheme
* [ ] Tracks event fired
* [x] Translatable text
* [ ] Snackbar notice displayed

**Out of bounds/rabbit holes**

*  Custom branding/calypso user flow - we'll look at that later - let's just get the connection working to start with.

**Event tracking:**

* [ ] Track connects
* [ ] Track disconnects
