### ISSUE TITLE
Site Claim

### ISSUE THREAD

**Issue by findingsimple** [woocommerce/google-listings-and-ads#10]
**User story:**

As a merchant
I want to claim my site within the Merchant Centre
So that I can reserve the URL I have previously verified for use with my Merchant Center account.

**Description:**

A Merchant, after verifying their ownership of a property, must also claim the site URL. A property/site can only be linked to a single Merchant Center account.

* If a claim attempt collides with an existing claim then the merchant needs to try and progress things through the MC Front End (manually use the claim URL button in MC)
* Claiming is done with the Content API
* Use Google credentials to claim site

**Technical**

* Refer to WooCommerce Shopping Integration Overview for example flow
* Claiming is done with the Content API

**Acceptance criteria:**

* [x] Merchant can claim existing url if it hasn't been claimed  - easy path
* [x] Merchant can reclaim existing url if it has already been claimed
  * [x] If reclaim succeeds - notify merchant their feed will be overridden if they proceed - the Step 1 continue button is clickable
  * [x] If claim fails - notify merchant that they will need to do some manual steps - direct them to merchant center/info - the Step 1 continue button is disabled (next steps TBC)

**Dependencies**

* [Full screen set up screen/page](https://github.com/woocommerce/google-for-woocommerce/issues/44)
* [Google Account Connection](https://github.com/woocommerce/google-for-woocommerce/issues/2)
* [Merchant Center Account](https://github.com/woocommerce/google-for-woocommerce/issues/8)
* [Site Verification](https://github.com/woocommerce/google-for-woocommerce/issues/9)

**Event tracking:**
* [ ] Track successful and unsuccessful claims (collisions etc.)
