### ISSUE TITLE
Enhance CI jobs in the GitHub Actions

### ISSUE THREAD

**Issue by eason9487** [woocommerce/google-listings-and-ads#1047]
## User story

As a developer, it'd be great

- if the CI could run jobs as fast as possible
- if the CI could run only the jobs that really need to be run
- if the CI could display colorful logs

## Technical

Some possible action items

- [x] Cancel the previous jobs for pull requests that have not been completed - #1224
    - Could be done with the workflow syntax `concurrency`
    - https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#concurrency
    - https://github.com/WordPress/wordpress-develop/blob/5.8.1/.github/workflows/coding-standards.yml#L37-L42
- [x] Remove `node` and `npm` requirements during the **PHP Unit Tests** job - #1140
    - [Prepare node](https://github.com/woocommerce/google-listings-and-ads/blob/42c13e5f3989e59c68efd2b59d1b0a7bf24c6b07/.github/workflows/php-unit-tests.yml#L18-L21)
    - [Prepare node](https://github.com/woocommerce/google-listings-and-ads/blob/42c13e5f3989e59c68efd2b59d1b0a7bf24c6b07/.github/workflows/php-unit-tests.yml#L44-L45)
    - [Build client bundles](https://github.com/woocommerce/google-listings-and-ads/blob/42c13e5f3989e59c68efd2b59d1b0a7bf24c6b07/.github/workflows/php-unit-tests.yml#L60-L61)
    - ~~❓  Not sure if the client files within `js/build/` are required when running PHP unit tests~~
- [x] Evaluate `npm ci` caching and skipping, as discussed in [this thread](https://github.com/woocommerce/google-listings-and-ads/pull/1133/#discussion_r761753593) - #1220
- [x] Only run **JavaScript and CSS Linting** job when the change files are ~~under the `js/src` folder~~ including any js/scss files for pull requests. - #1326
- [x] Only run **PHP Coding Standards** job when the change files are ~~under the `src` folders~~ including any PHP files for pull requests. - #1326
- [x] Adjust **PHP Coding Standards** job to cover [all listed PHP files](https://github.com/woocommerce/google-listings-and-ads/blob/1.11.1/phpcs.xml.dist#L115-L117) by `./*`. The details can be found in [this comment](https://github.com/woocommerce/google-listings-and-ads/issues/1047#issuecomment-1065090293). - #1320
- [x] Clean up Travis CI related setup - #1056
- [x] Make the logs have colors - #1137
    Colorless workflows are:
    - [bundle-size](https://github.com/woocommerce/google-listings-and-ads/blob/42c13e5f3989e59c68efd2b59d1b0a7bf24c6b07/.github/workflows/bundle-size.yml#L55-L58)
    - [js-css-linting](https://github.com/woocommerce/google-listings-and-ads/blob/42c13e5f3989e59c68efd2b59d1b0a7bf24c6b07/.github/workflows/js-css-linting.yml#L62-L63)
    - [js-unit-tests](https://github.com/woocommerce/google-listings-and-ads/blob/42c13e5f3989e59c68efd2b59d1b0a7bf24c6b07/.github/workflows/js-unit-tests.yml#L21-L22)
- [x] Avoid the [JavaScript and CSS linting failure](https://github.com/woocommerce/google-listings-and-ads/runs/4366453291?check_suite_focus=true#step:5:6) due to insufficient permissions - #1223

**Comment by tomalec** [comment]
> - [x] Clean up Travis CI related setup

👍

**Comment by eason9487** [comment]
> ❓ Not sure if the client files within `js/build/` are required when running PHP unit tests

After discussing it on team's dev call, these client files should not be needed when running PHP unit tests. So we could try to dynamically create mocked files, or just add the mocked files to git and copy them to `js/build/`. And it expects to save about 1.2 ~ 2 minutes.

**Comment by mikkamp** [comment]
@eason9487 Seems like there are just two pending things left here. But I wanted to comment on the following point:

> Only run PHP Coding Standards job when the change files are under the src folders for pull requests

Seems we are only checking code standards for the `./src` folder: https://github.com/woocommerce/google-listings-and-ads/blob/1.11.1/.github/workflows/php-coding-standards.yml#L27

But we have additional php files which we should be checking, I think we can use the same list as [this one](https://github.com/woocommerce/google-listings-and-ads/blob/1.11.1/package.json#L101-L107)

Or alternatively we can just run phpcs for `./*` our [config file](https://github.com/woocommerce/google-listings-and-ads/blob/1.11.1/phpcs.xml.dist#L115-L117) already specifies a list of folders to ignore, at most we can add additional ones there like the `js` folder.

Because we missed this the coupon files in the views folder are full of errors (these were contributed by Google so the automated check would have been helpful).

**Comment by eason9487** [comment]
@mikkamp, thanks for the information!

> But we have additional php files which we should be checking, [...]

I think we could add the missing folders/files during the next two weeks. I will add it to the action items.

**Comment by mikkamp** [comment]
I've created PR #1320 which does a stricter check (includes checking warning) and checks all PHP files. That will make it harder to check if this needs to be run for all PR's but it's relatively quick to run, so it might not be much of an issue.

**Comment by eason9487** [comment]
Thank you all for helping with these enhancements! 🙇‍♂️ 
Closing this issue for that all action items have been implemented. 🎉
