### ISSUE TITLE
UX improvements on account connections

### ISSUE THREAD

**Issue by ecgan** [woocommerce/google-listings-and-ads#1065]
## User story

This is the main issue to track the work of UX improvement on account connections.

Currently, Step 1 (account connections) of the Onboarding Flow has one of the steepest drop-offs in the funnel. Our goal with these UX improvements is to reduce that drop.

Design with explanation:

![image](https://user-images.githubusercontent.com/417342/139102179-4d138545-be24-4df2-81cd-1d660146b296.png)

Animated GIF:

![account-setup-step-1](https://user-images.githubusercontent.com/417342/139102811-66546859-0361-46d5-982a-a2a81e662fb5.gif)

UI front-end changes:

- [x] WordPress.com account card (done in #1068)
- [x] Google account card (done in #1072)
- [x] Allow user to switch Google account after connected (done in #1072)
- [x] Google Merchant Center account card (done in https://github.com/woocommerce/google-listings-and-ads/pull/1094)
- [x] "Lightbulb" tip for Google Merchant Center on the left hand side (done in #1075)
- [x] Disconnect GMC when disconnecting / switching Google account (done in https://github.com/woocommerce/google-listings-and-ads/pull/1109)
- [x] Display GMC account name and domain in GMC cards (done in https://github.com/woocommerce/google-listings-and-ads/pull/1112)

Back-end changes:

- [x] https://github.com/woocommerce/google-listings-and-ads/pull/1092
- [ ] (Non-blocking / good to have) Add name and domain to connected GMC account connection

WCS changes: 

- [x] Add name and domain to Merchant API response #1840 1840-gh-Automattic/woocommerce-connect-server
- [x] Use Manager token for MCA requests #1855 1855-gh-Automattic/woocommerce-connect-server

## Technical

There may be some overlap of work or impacted area with the on-going partial oauth project led by @eason9487.

## Figma link

2a91c-pb

## Internal project thread link

pcTzPl-6u-p2

## Acceptance criteria

The UI of Setup MC Step 1 should reflect the above designs.
