### ISSUE TITLE
Multi-country targeting for Google Ads campaign

### ISSUE THREAD

**Issue by eason9487** [woocommerce/google-listings-and-ads#1248]
### Objective 

Enable merchants to target multiple countries in a single Google Ads campaign, reducing management overhead of campaign/budget and increasing the ability of campaign algorithm to scale.

### Overview

Change the functionality of campaign creation and editing to make it be able to specify multiple countries in a single Google Ads campaign.

![image](https://user-images.githubusercontent.com/17420811/154234977-da9b289f-6bb2-4393-a2c0-f5172b891da1.png)

### The current state of the system

Currently, it only allows merchants to select one country when creating a campaign. It also results in a very inefficient campaign setup experience, especially if the store ships to all 22 EU countries or worldwide.

![image](https://user-images.githubusercontent.com/17420811/154233583-e518082e-87ed-4643-b86b-fb9fc53effd4.png)

## Terminology

💡  Scope: this project and all related issues/pull requests

- The "old campaign(s)" refers to the existing campaigns created **before** releasing this feature.
- The "new campaign(s)" refers to the campaigns created **after** this feature is finished.

## Technical

💡  We will create a shared branch `feature/1248-multi-country-targeting-campaign`. All relevant developments should be branched from it and merged back to it. And open a PR to merge the shared branch to `develop` once the overall feature gets ready to release.

💡  The old campaigns will still be presented in a single-selected country UI when editing. The rest of relevant pages will be presented on a multi-country basis.

### Frontend

The UI changes should be applied to campaign creation and edit pages. All frontend routings will stay with the current.

#### Phase 1

- 📌  **Move the free ads credit box to step 1 of ads account setup.**
    - Implemented in #1253
    - Before
    ![image](https://user-images.githubusercontent.com/17420811/154430320-b99d4db2-ed72-4c57-88bb-5f07cf3e9c62.png)
    - After
    ![image](https://user-images.githubusercontent.com/17420811/154430442-0273dd81-55dc-4bfb-a455-eb1f226ec56a.png)
    - This box will only be displayed in step 1 of ads setup flow. It won't be shown on the single-page campaign creation/edit page. (Confirmed with Jill)
    - :warning: The copies have been changed after #1217 and the updated copies should be the latest. So the copies in the box will be different between implementation and visual design.
- 📌  **Separate edit UI for both old and new campaigns.**
    - Implemented in #1268
    - Edit an old campaign
    ![image](https://user-images.githubusercontent.com/17420811/154432429-bcb6ff15-0b88-412e-9d21-ddb28e98661d.png)
    - Edit a new campaign
    ![image](https://user-images.githubusercontent.com/17420811/154432330-8b7658b1-a8ea-433b-bad1-13d4d0e34539.png)
    - :warning: It doesn't include multiple selector of countries. It's separately handled during phase 2.
- 📌  **Change the rest of UI to fit with new design.**
    - Implemented in #1268
    - After
    ![2022-02-17 16 14 40](https://user-images.githubusercontent.com/17420811/154434048-957e22e1-4e7d-4c5d-9fe2-2adb9d24d5a9.png)
    - Add the disabled status of the whole budget section.
    - Update the copies for the circled-up places.
    - :warning: It doesn't include multiple selector of countries. It's separately handled during phase 2.
- 📌  **Pre-populating the Audience field.**
    - Implemented in #1300
    - Pre-populate the **Audience** field with the countries that the merchant previously selected as part of their Merchant Center setup.
        ![image](https://user-images.githubusercontent.com/17420811/157208914-d0c2fddd-faa9-43be-bab3-33aa1d9cf85e.png)
- 📌  **Mock new API design with mocking data.**
    - Implemented in #1271
    - The proposed API designs are listed at below **Backend** section. Mocking API:
        - `GET ads/campaigns`
        - `POST ads/campaigns`
        - `GET ads/campaigns/budget-recommendation`
- 📌  **Integrate `ads/campaigns` related endpoints with mocking API.**
    - Implemented in #1273
    - Add `allowMultiple` property to each campaign entity when receiving API data in the *actions.js*.
    - Create a new campaign with multiple countries.
    - Display countries according to single country or multiple countries when editing a campaign
- 📌  **Integrate `ads/campaigns/budget-recommendation` related endpoints with mocking API.**
    - Implemented in #1275
    - After
    ![2022-02-17 16 24 53](https://user-images.githubusercontent.com/17420811/154435401-6aafe09f-ffe9-4395-9906-253dacd76c59.png)
    - When selecting one or more countries, the circled-up wording is different.
    - If the merchant selects more than one country, the budget recommendation takes the highest country out from the selected countries.
    When looking for the highest one, it should only consider the upper bound value. For example, a merchant selected Brunei (5-20 USD) and Croatia (10-15 USD), then the budget recommendation should be (5-20 USD).(Confirmed with Jill)

#### Phase 2

- 📌 **Integrate new API design with finished implementations.**
    - Revert all changes in 1b92a8522ad4d3e8d7805ad0cc26658663a773be
       - [x] `GET ads/campaigns/budget-recommendation/:country-code` #1299 
       - [x] `GET ads/campaigns` #1338
       - [x] `POST ads/campaigns` #1338
    - [x] Check if the frontend implementations work correctly with API.
- 📌 **Replace the single country selection component with the dedicated component.**
    - Get continents data from API
    - Implement multi-country selection component by `<TreeSelectControl>` component.

#### Related projects

- `<TreeSelectControl>` component (pcTzPl-fg-p2)
    - This project requires the component to select multiple targeting countries.
    - All features in milestone 1.
    - Part of features in milestone 2:
        - Allow clicking on "X" in the tag to remove the value.
        - Search to filter the tree nodes.
        - Expand/collapse tree nodes.
    - Part of features in milestone 3a:
        - Partially-checked checkbox.
        - Allow specifying a limit for the number of tags to be displayed.

#### GLA APIs

We will continue to use the existing APIs and change them to multi-country targeting implementation.

- **GET** `ads/campaigns`
    - The returned data contain both old campaigns and new campaigns.
    - Should contain multiple targeting countries for the new campaigns.
    - Should be able to distinguish between old and new campaigns.
    - Proposed API changes
        - Old response
            ```json 
            [
                {
                    "id": 16165825406,
                    "name": "Campaign 2022-02-09 09:31:52",
                    "status": "enabled",
                    "amount": 50,
                    "country": "TW"
                },
                {
                    "id": 16178695424,
                    "name": "Campaign 2022-02-10 06:29:08",
                    "status": "enabled",
                    "amount": 245,
                    "country": "GB"
                },
                {
                    "id": 16215030217,
                    "name": "Campaign 2022-02-14 06:42:36",
                    "status": "enabled",
                    "amount": 245,
                    "country": "GB"
                }
            ]
            ```
        - 🆕 New response
            ```json 
            [
                {
                    "id": 16165825406,
                    "name": "Campaign 2022-02-09 09:31:52",
                    "status": "enabled",
                    "amount": 50,
                    "country": "TW",
                    "targeted_locations": []
                },
                {
                    "id": 16178695424,
                    "name": "Campaign 2022-02-10 06:29:08",
                    "status": "enabled",
                    "amount": 245,
                    "country": "TW",
                    "targeted_locations": ["TW", "GB"]
                },
                {
                    "id": 16215030217,
                    "name": "Campaign 2022-02-14 06:42:36",
                    "status": "enabled",
                    "amount": 245,
                    "country": "TW",
                    "targeted_locations": ["GB", "US"]
                }
            ]
            ```
        - 📝 It will be an `old campaign` if the `targeted_locations` is an empty array.
- **GET** `ads/campaigns/:id`
    - Currently frontend side is not using this API. We could remove this endpoint from backend.
    - The returned data be the same entity structure as `ads/campaigns`.
    - Proposed API changes
        - 🆕 New response
            ```json 
            [
                {
                    "id": 16178695424,
                    "name": "Campaign 2022-02-10 06:29:08",
                    "status": "enabled",
                    "amount": 245,
                    "country": "TW",
                    "targeted_locations": ["TW", "GB"]
                }
            ]
            ```
- **POST** `ads/campaigns`
    - Accepts creating with multiple targeting countries.
    - The returned data should be the same entity structure as `ads/campaigns`.
    - Proposed API changes
        - Old
            - Request body
                ```json
                {
                    "amount": 245,
                    "country": "GB"
                }
                ```
            - Response
                ```json
                {
                    "id": 16178695424,
                    "name": "Campaign 2022-02-10 06:29:08",
                    "status": "enabled",
                    "amount": 245,
                    "country": "GB"
                }
                ```
        - 🆕 New
            - Request body
                ```json
                {
                    "amount": 245,
                    "targeted_locations": ["TW", "GB"]
                }
                ```
            - Response
                ```json
                {
                    "id": 16178695424,
                    "name": "Campaign 2022-02-10 06:29:08",
                    "status": "enabled",
                    "amount": 245,
                    "country": "TW",
                    "targeted_locations": ["TW", "GB"]
                }
                ```
- **PATCH** `ads/campaigns/:id`
    - No adjustment is needed since it only allows update budget and enabled status when editing.
- **DELETE** `ads/campaigns/:id`
    - Should also delete the associated targeting countries when deleting a new campaign.
- **GET** `ads/campaigns/budget-recommendation/:country-code`
    - Change the endpoint to `ads/campaigns/budget-recommendation`.
    - Accepts querying multiple targeting countries.
    - The returned data should contain recommended budget ranges for all querying countries.
    - Proposed API changes
        - Old
            - Request
                ```
                GET ads/campaigns/budget-recommendation/:country-code
                ```
            - Response
                ```json
                {
                    "currency": "TWD",
                    "country_code": "TW",
                    "daily_budget_low": "95",
                    "daily_budget_high": "255"
                }
                ```
        - 🆕  New
            - Request
                ```
                GET ads/campaigns/budget-recommendation?country_codes[]=TW&country_codes[]=US&country_codes[]=GB
                ```
            - Response
                ```json
                {
                    "currency": "EUR",
                    "recommendations": [
                        {
                            "country": "US",
                            "daily_budget_low": 10,
                            "daily_budget_high": 25
                        },
                        {
                            "country": "GB",
                            "daily_budget_low": 5,
                            "daily_budget_high": 20
                        },
                        {
                            "country": "IE",
                            "daily_budget_low": 5,
                            "daily_budget_high": 15
                        }
                    ]
                }
                ```
- **GET** `mc/countries`
    - The returned data should contain continents for frontend to group countries on UI.
    - **API changes**
      - Add a new query parameter `continents`, the response will include continents data if the parameter is set to true.
      - Proposed API changes
        - Old
          - Request
              ```
              GET mc/countries
              ```
          - Response
              ```json
              {
                  "US": {
                      "name": "United States",
                      "currency": "USD"
                  },
                 "GB": {
                     "name": "United Kingdom",
                     "currency": "GBP"
                 },
                 "TW": {
                     "name": "Taiwan",
                     "currency": "TWD"
                 }
             }
              ```
        - 🆕  New
          - With `continents=true` parameter
            - Request
                ```
                GET mc/countries?continents=true
                ```
            - Response
                ```
                {
                    "countries": {
                        "US": {
                            "name": "United States",
                            "currency": "USD"
                        },
                       "GB": {
                           "name": "United Kingdom",
                           "currency": "GBP"
                       },
                       "TW": {
                           "name": "Taiwan",
                           "currency": "TWD"
                       }
                    },
                    "continents": {
                        "AF": {
                            "name": "Africa",
                            "countries": [
                                "AO",
                                "BF",
                                "BI",
                            ]
                        }
                    }
                }
                ```
          - Without `continents` parameter
            - Request
                ```
                GET mc/countries
                ```
            - Response
                ```
                {
                    "countries": {
                        "US": {
                            "name": "United States",
                            "currency": "USD"
                        },
                       "GB": {
                           "name": "United Kingdom",
                           "currency": "GBP"
                       },
                       "TW": {
                           "name": "Taiwan",
                           "currency": "TWD"
                       }
                    }
                }
                ```
#### Potentially related projects

- WooCommerce Shipping Zones Integration #1111
    - It also needs to use continents data through WooCommerce APIs.
    - Google API uses geolocation to set targeting countries (including cities, states, and provinces). In GLA codebase we use country code (ISO 3166-1 alpha-2) across database, backend, and frontend. So it will need to map Google’s geolocation codes to GLA’s country codes. #1282
- Performance Max (PMax) Migration
    - It also relates to campaigns. (Smart Shopping campaigns)

### Google documents

- Google API
  - https://developers.google.com/adwords/api/docs/guides/shopping
  - https://developers.google.com/google-ads/api/docs/targeting/location-targeting
  - https://developers.google.com/google-ads/api/reference/rpc/v9/CampaignCriterion
- Google REST API spec
  - https://developers.google.com/google-ads/api/rest/reference/rest/v9/customers.campaignCriteria#resource:-campaigncriterion
  - https://developers.google.com/google-ads/api/rest/reference/rest/v9/customers.campaignCriteria#LocationInfo

### Project: 

pcTzPl-bo-p2

### Figma: 

eQ9O4m2flzrcAiDMXkOW0m-fi-5429%3A115711
