### ISSUE TITLE
Product Sync: Product Attributes

### ISSUE THREAD

**Issue by findingsimple** [woocommerce/google-listings-and-ads#16]
**User story:**

As a merchant
I want to be able to edit product attributes required by Google
So that my product data is approved and available for listings.

**Description:**

Internal reference doc pb0Spc-Ze-p2

A summary of which is...

tl;dr;

* Products have [60+ attributes](https://href.li/?https://support.google.com/merchants/answer/7052112#quick-reference), of which approximately a dozen are always required, another 30 are required when certain conditions are met, and the rest are optional (but encouraged in some cases for data quality and increased likelihood of approval).
* Products also belong to a category ([full list](https://href.li/?http://www.google.com/basepages/producttype/taxonomy-with-ids.en-US.txt)), which is assigned automatically based on product attributes (the more information, the better), but the predicted category can be overridden [in certain situations](https://href.li/?https://support.google.com/merchants/answer/6324436?hl=en).
* Of the required attributes:
  * 7 can be mapped from WooCommerce product attributes: id, title, description, link, image_link, availability and price (only four are required fields in Woo)
  * ~5 will require prior configuration or additional WooCommerce fields (GTIN/MPN, brand, shipping, taxes).
* Of the remaining attributes, a handful could be guessed based on WooCommerce product attributes (e.g., additional images, basic shipping) but the vast majority would need to be either configured (mapping [custom Woo attributes](https://href.li/?https://docs.woocommerce.com/document/managing-products/#attributes-section) to Product attributes) or manually entered (adding extra data entry fields to the product form or establishing an inheritable global value for the store or category). Some data could also be gleaned if certain extensions are activated on the store (Min/Max Quantities, Product Bundles, etc).
* There’s an [existing extension](https://href.li/?https://woocommerce.com/products/google-product-feed/) available has product feed functionality but it uses the pull method (XML feeds hosted on the site). We are instead going to be using the push method for adding products to the merchant center via the Content API.
* Facebook for WooCommerce extension has prior art for product sync-ing with Facebook.

Reference Links

* [Full list of Product API required and recommended attributes](https://href.li/?https://support.google.com/merchants/answer/7052112?hl=en&visit_id=637334259431566461-482412874&rd=1)
* [WooCommerce products documentation](https://href.li/?https://docs.woocommerce.com/document/managing-products/)
* [Google Product Feed extension documentation](https://href.li/?https://docs.woocommerce.com/document/google-product-feed/)

**Acceptance criteria:**

* [x] Must support variable products

Very initial implementation of this should focus on the minimum required fields that are needed to get us to testing... we can create follow-up issues for additional fields and get to them as quickly as we can before release. But we should focus on hitting that beta release deadline.

* [x] id
* [x] title
* [x] description
* [x] link
* [x] image_link
* [x] availability
* [x] price

Enhanced Listings / strongly encouraged

* [x] GTIN/MPN
* [x] Brand (Integrate with WC Brands)
* [x] additional_image_link
* [x] gender
* [x] size
* [x] color
* [x] age_group
* [x] adult
* [x] size_type
* [x] size_system
* [x] material
* [x] pattern
* [x] condition
* [x] multipack
* [x] is_bundle

**Technical**

* Like the facebook extension it will probably be useful to offer different levels of "default" attributes where relevant e.g.
  * Site Level Attributes (defaults)
  * Category Level Attributes (overrides the above)
  * Product Level Attributes (overrides the above)
* We will stick to using site language and currency for v1 BUT push multiple times for each target countries
* We will use site-wide shipping settings
* We will use site-wide tax settings

**Dependencies**

* Merchant Center Account

**Rabit Holes**

* Do not worry about things like "recommended" formatting of titles for v1

**Event tracking:**

TBD
