### ISSUE TITLE
Update Ads library to support API V11

### ISSUE THREAD

**Issue by mikkamp** [woocommerce/google-listings-and-ads#1600]
For the PMax migration we need make use of the [Campaign.PerformanceMaxUpgrade](https://developers.google.com/google-ads/api/reference/rpc/v11/Campaign.PerformanceMaxUpgrade) field, which means we need to support API V11. We are currently still using V11 because V10 required bumping minimum PHP support to 7.4 (currently still at 7.3).

A similar PR can be created as the [V8 > V9](https://github.com/woocommerce/google-listings-and-ads/pull/1204) upgrade. We also want to update the Merchant Center library since it shares a lot of common packages with the Google Ads library. Updating will also resolve dependabot PR's like this [one](https://github.com/woocommerce/google-listings-and-ads/pull/1571).

### Tasks
- [x] Upgrade [google-ads-php](https://github.com/googleads/google-ads-php/releases/tag/v16.0.0) composer package to 16.0.0
- [x] Upgrade the apiclient and apiclient services packages
- [x] Update the overwritten Ads classes in src/Google/Ads/ to support V11
- [x] Change any imports of `Google\Ads\GoogleAds\V9` to `V11`
- [x] Remove old versions of Ads library (V8 - V10) in [composer.json](https://github.com/woocommerce/google-listings-and-ads/blob/2.0.1/composer.json#L64)
- [x] Bump [cleanup script to V11](https://github.com/woocommerce/google-listings-and-ads/blob/2.0.1/bin/GoogleAdsCleanupServices.php#L25) and ensure it preserves all the right files.
- [x] Bump minimum PHP version to 7.4 in [composer.json](https://github.com/woocommerce/google-listings-and-ads/blob/2.0.1/composer.json#L52) + [#](https://github.com/woocommerce/google-listings-and-ads/blob/2.0.1/composer.json#L8) and [plugin requirements](https://github.com/woocommerce/google-listings-and-ads/blob/2.0.1/google-listings-and-ads.php#L32).
- [x] Bump minimum PHP version to 7.4 in plugin headers/readme's/documentation/wiki
