### ISSUE TITLE
Streamlined Free Listings plus Paid Ads for the onboarding flow

### ISSUE THREAD

**Issue by eason9487** [woocommerce/google-listings-and-ads#1610]
## Objective

- An onboarding flow for the integration offers merchants a choice of selecting Free Listings plus Paid Ads.
- The ability for merchants to:
   - preview the ads or campaigns they are about to launch,
   - know how many products will be synced to Google Merchant Center,
   - and set up billing for their Google Ads account via a popup.

💡 We will create a shared branch `feature/1610-streamlined-onboarding`. All relevant developments should be branched from it and merged back into it. And open a PR to merge the shared branch to develop once the overall features get ready to release.

## Terminology

- FL: Free Listings

## Technical - Frontend

The UI changes are mainly applied to the onboarding flow, and some shared components used in the Edit free listings page and Set up paid campaign page might be changed respectively.

Most requirements are listed in pcTzPl-Kc-p2#the-flow-breakdown and the related Figma document. This list only outlines other changes besides the p2 post.

### 📌 Adjust the setting sections in the onboarding steps

- [x] Merge the original step 3 into step 2 - #1616
- [x] Remove the auto-fill mechanism of shipping rates - #1616
- [x] Add another submit button to step 4 for skipping paid ads creation - #1619

### 📌 Update other UI changes

Refer to **Landing Page**, **Step 1: Set up accounts**, **Step 2: Configure product listings**, **Step 3: Confirm store requirements**, and **Submission Success** in pcTzPl-Kc-p2#the-flow-breakdown

- [x] Logo icons in some account cards - #1618
- [x] Layouts and copywriting on the landing page - #1618
- [x] Layouts and copywriting of steps 1~3 in the onboarding flow - #1618
- [x] Add [CSS disclaimer](https://github.com/woocommerce/google-listings-and-ads/issues/1610#issuecomment-1246442668) to step 1 - #1679 
- [x] FAQ card in step 4 - #1679 
- [x] Submission success modal in the product feed page - #1679 

### 📌 Product feed status section

Refer to **Step 4.1: Setting up Paid Ads** in pcTzPl-Kc-p2#the-flow-breakdown

- [x] Implement this section UI - #1638 

### 📌 Boost product listings section

Refer to **Card 2 in Step 4: Complete your campaign with paid ads** in pcTzPl-Kc-p2#the-flow-breakdown

- [x] Section UI and the interactions of "skip" and "continue" buttons - #1649 
- [x] Dynamically composite the ad previews - #1650

Site logo: https://wordpress.com/support/site-logo/

### 📌 Google Ads account section

Refer to **Step 4.1: Setting up Paid Ads** in pcTzPl-Kc-p2#the-flow-breakdown

- [x] Add a button to disconnect Google Ads account - #1654
- [x] Add an external link to open Google's management page of connected Google Ads account - #1654
- [x] Handle the page redirection for the authorization of Google account - #1654

### 📌 Ads audience and budget sections

Refer to **Step 4.1: Setting up Paid Ads** in pcTzPl-Kc-p2#the-flow-breakdown

- [x] Tweak audience and budget UI - #1655
- [x] Handle the form data of campaign creation and forward it to the upper layer - #1655

### 📌 Billing Ads card

Refer to **Step 4.2: Set up Billing Ads** in pcTzPl-Kc-p2#the-flow-breakdown

- [x] Open a popup window for setting up billing, and the popup window should be resizable. - #1677
- [x] Card UI for notifying the successfully added billing method. - #1677
- [x] Add an alternative link for opening the billing setup page. - #1677
- [x] Complete the onboarding with paid ads setup. - #1677

### 📌 Post-onboarding setup flow

- [x] Add ad previews to the post-onboarding ads setup flow. - #1721

### 📌 Client states management and API integration

- [x] Fetch the number of products to be synced from a new API for the product feed status section - #1706
- [x] Fetch the product and site data from API for compositing the ad previews - #1692
- [x] Store/restore the selected countries and the entered budget when leaving/entering step 4 - #1683
- [x] Store/restore the switched state of skipping or continuing the paid ads setup when leaving/entering step 4 - #1683

### <a href="#event-tracking" id="event-tracking">📌 Event tracking</a>

- [x] Add event tracking - #1689

![2022-09-21 15 35 55](https://user-images.githubusercontent.com/17420811/191444603-805eddd5-566c-47ee-8a64-6769e31597c5.png)
![2022-09-21 15 36 36](https://user-images.githubusercontent.com/17420811/191444621-330a8009-5684-4c90-9196-4ef2424e2f73.png)

- `gla_onboarding_complete_button_click` for **A** and **C** with these properties:
   - `opened_paid_ads_setup`: yes | no
   - `google_ads_account_status`: unknown | connected | disconnected | incomplete
   - `billing_method_status`: unknown | pending | approved | cancelled
   - `campaign_form_validation`: unknown | valid | invalid
   - The unknown status is used when the paid ads setup is not opened.
- `gla_onboarding_open_paid_ads_setup_button_click` for **B**
- `gla_onboarding_complete_with_paid_ads_button_click` for **D**
 
### ~<a href="#be-task0" id="be-task0">#</a> 📌 A new API for onboarding completed~

~In the previous onboarding flow the last API frontend calls is `mc/settings/sync`. It will set the timestamp to the option `gla_mc_setup_completed_at`. In the new onboarding flow, this API will be called again in step 4 to ensure all settings are updated if a merchant changes anything after they enter step 4 and then back to steps 1~3.~

~We decide to create a new API `mc/setup/complete` and move the logic of setting the timestamp to the option `gla_mc_setup_completed_at` to this new API. (`MC_SETUP_COMPLETED_AT` in PHP code)~

- ~Create a new API `POST mc/setup/complete` to set the timestamp to the option `gla_mc_setup_completed_at`.~
    - ~Payload: No payload~
    - ~Response:~
        - ~Status: `201 Created`~
        - ~Data: No data~
- ~In the API `mc/settings/sync`, do not set the timestamp to the option `gla_mc_setup_completed_at`.~

### ~<a href="#be-task01" id="be-task01">#</a> 📌 Extends `mc/product-statistics` API to return # of syncable products~

~In the step 4 of the new onboarding flow, we will display Your product listings are ready to be uploaded • # products on the first card. The # in the wording is the number of products that are ready to be synced. After some discussion on the project post (pcTzPl-I1-p2#comment-1604) we decide the extend an existing API mc/product-statistics and return a new data syncable_products in the response data. We can reuse an existing method [find_sync_ready_products](https://href.li/?https://github.com/woocommerce/google-listings-and-ads/blob/c2b0b45bd5d406bcd0c374252387390f76fae521/src/Product/ProductRepository.php#L148-L152) in src/Product/ProductRepository.phpWe will create two new APIs, GET mc/syncable-products-count and POST mc/syncable-products-count for this requirement.~

- ~In API mc/product-statistics, modify the logic to return the following new data:~
    ```js
    {
        "timestamp": null,
        "statistics": null,
        "scheduled_sync": 0,
        "syncable_products": 29
    }
    ```
- ~Revisit the logic of display product overview in the GLA product feed page. The sum of the products there should be the number of syncable products, rather the number of total products in WooCommerce.~

### <a href="#be-task1" id="be-task1">#</a> 📌 Syncable Products Count

In the step 4 of the new onboarding flow, we will display **_Your product listings are ready to be uploaded • # products_** on the first card. The `#` in the wording is the number of products that are ready to be synced. We will create two new APIs, `GET mc/syncable-products-count` and `POST mc/syncable-products-count` for this requirement.

- [x] New API to retrieve the number of syncable products: `GET mc/syncable-products-count` - #1699
    - If there are data in the database:
        ```json
        {
            "count": 20
        }
        ```
    - If there are no data or the data are not yet ready in the database, return null:
        ```json
        {
            "count": null
        }
        ```
- [x] New API to schedule a job to calculate the number of syncable products: `POST mc/syncable-products-count`
    - No parameters required. - #1699
    - ✏️ **_Frontend should call it right after the user enters the onboarding flow._**
- [x] Group variation products as one for the same parents when counting syncable products. - #1713
- [ ] Revisit the logic of display product overview in the GLA product feed page. The sum of the products there should be the number of syncable products, rather the number of total products in WooCommerce. - #1728
    - This is a follow-up issue so it can be excluded in the first release of this project.

### <a href="#be-task2" id="be-task2">#</a> 📌 Verify all the logics depend on `gla_ads_setup_completed_at`

Frontend will call the API `ads/setup/complete` if merchants set up Paid Ads in step 4, and this API will set the timestamp to the option `gla_ads_setup_completed_at`. (`ADS_SETUP_COMPLETED_AT` in PHP code)

- [x] Verify all the logics depend on `gla_ads_setup_completed_at`, update code if needed.

### <a href="#be-task3" id="be-task3">#</a> 📌 Update the step name logic returned by the API `mc/setup`

Since some of the steps in the new onboarding flow are changed in order or merged together.

- [x] Update the step name logic returned by the API `mc/setup`. #1619 

### <a href="#be-task4" id="be-task4">#</a> 📌 Return merchants key product data (e.g. bestselling)

If we aim at returning the bestselling product, we don’t need to add a new API for it. Instead, we can extend the existing API `mc/product-feed` and doing some extra meta query to get the product that has largest total sales. However, we would need to add extra returned data such as product image and price for the API `mc/product-feed`. More information can be found in pcTzPl-I1-p2#comment-1533.

- [x] Extend `mc/product-feed` API to be able to filter the bestselling product - #1681
  - New value `total_sales` for the query parameter `orderby`.
  - Use parameters `per_page`=`1`, `orderby`=`total_sales`, and `order`=`desc` to get the bestselling product.

Example:

```js
// GET mc/product-feed?per_page=1&orderby=total_sales&order=desc

{
    "products": [
        {
            "id": 279,
            "title": "Product title",
            "visible": true,
            "status": "disapproved",
            "errors": [],
            "price": "10", // new data
            "image_url": "https://example.com/example.png", // new data
        }
    ],
    "total": 28,
    "page": "1"
}
```

- [x] Add `siteLogoUrl` into `glaData` for frontend to use - #1681

Frontend needs to display the site logo, instead of putting it in `product-feed` AP, it's more appropriate to add it in `glaData.siteLogoUrl`.

Example on how to get the custom site logo url:

```php
wp_get_attachment_image_url( get_theme_mod( 'custom_logo' ), 'full' );
```

Note that if the site admin does not upload a custom site logo, the above code will return `false`.
In `glaData.siteLogoUrl` it will be `null`.

### Project: 

- Project thread: pcTzPl-I1-p2
- Design thread: pcTzPl-Kc-p2

### Figma: 

- fqR0EHi63lWahRcVTKCcba-fi-4%3A36753

**Comment by nikivias** [comment]
Hello hello, we need to do a small update to Step 1 (Connect accounts) of the FL+ Ads flow. Please see the original conversation [here](https://docs.google.com/document/d/1dcyZN6t0AgG36TCqV29luRLzrCI9ArS6VUHDsVoU5Yo/edit?disco=AAAAdRYklQE)

The update is to add a CSS disclaimer on the said step/page. As per Google: _"Our requirement is that platform’s UI should include instructions on how to work with a third-party Comparison Shopping Service early in the onboarding flow. We have flexibility with the language, as long as it is clear to merchants."_

The change has been added into [the design on Figma](https://www.figma.com/file/fqR0EHi63lWahRcVTKCcba/Google-Listings-%26-Ads-v2.x?node-id=449%3A80811)

@eason9487
