### ISSUE TITLE
Run PHPCS for unit test code

### ISSUE THREAD

**Issue by mikkamp** [woocommerce/google-listings-and-ads#1623]
## User story

Currently the PHPCS rules are ignored for all the code in the unit tests folder. However it can be useful to keep code standards for the unit tests as well, especially the rules for spacing and code formatting which make it easier to read the code.

The suggestion is to create a second PHPCS configuration file which will be used for checking the code in the unit tests folder. Rules for doc blocks can be turned off as well as any other rules which don't apply directly to unit tests.

### Tasks to complete

- [x] Create a second PHPCS configuration file for unit tests.
- [x] Ensure IDE's will be able to automatically pick up the configuration files.
- [x] Add a second PHPCS check in the GitHub actions which uses the configuration file for unit tests.
- [x] Make sure the tests folder is not excluded from detecting any PHP changes in GitHub actions.
- [x] Fix the current unit tests to pass PHPCS rules.
