### ISSUE TITLE
Target Country / Audience

### ISSUE THREAD

**Issue by findingsimple** [woocommerce/google-listings-and-ads#17]
**User story:**

As a merchant
I want to be able to select a target country (or countries)
So that I can reach an appropriate audience for my listings.

**Description:**

Merchants will have the option to select which countries to target with their listing/s.

![Screen Shot 2020-11-03 at 3 19 37 pm](https://user-images.githubusercontent.com/355014/97950873-35f81100-1de8-11eb-8f29-f0d595c92ce8.png)

Supported languages, countries, and currencies are listed here https://support.google.com/merchants/answer/160637?hl=en 

**Technical**

* Site language is based on the standard WordPress Site language setting (see below)
* Site language is not editable but we'll provide a tooltip/link to Site Language settings if merchange want more context

![site-language](https://user-images.githubusercontent.com/355014/97950998-8d967c80-1de8-11eb-982b-269c17f952d3.png)

**Acceptance criteria:**

* [x] Merchant can select 1 or more countries
* [x] Optionally - based on store currency reorder list
* [x] Don't allow targeting of Beta countries
* [x] Merchant must choose at least 1 target country

**Out of bounds/rabbit holes**

* Provided the site currency is supported the target country currency is not a concern as Google will do currency conversion and display both prices in listings.
* Provided the site language is supported, the Merchant can select to target any supported country. (Obviously targeting dominant languages in a country is better.)
* It will be up to the merchant to make sure they have appropriate tax and shipping settings configured in the MC otherwise they risk their offers being disapproved

**Dependencies**

* https://github.com/woocommerce/google-for-woocommerce/issues/27

**Event tracking:** 

* [ ] Track what target countries merchants choose
