### ISSUE TITLE
PMax Assets

### ISSUE THREAD

**Issue by jorgemd24** [woocommerce/google-listings-and-ads#1780]
This feature implements PMax Assets.

Project Thread: [pcTzPl-HY-p2](pcTzPl-12o-p2)
Technical Exploration: pcTzPl-1c9-p2

## Terminology
[Assets](https://href.li/?https://developers.google.com/google-ads/api/fields/v11/asset): headlines, descriptions, logos, images, Youtube links etc.
[Asset Group](https://href.li/?https://developers.google.com/google-ads/api/fields/v11/asset_group): It’s a group that contains the assets and is linked to a campaign and a Final URL.
[Assets Group Assets](https://href.li/?https://developers.google.com/google-ads/api/fields/v11/asset_group_asset): It’s the link between the Assets and Asset Groups.

## Figma link

[fqR0EHi63lWahRcVTKCcba-fi.x?t=whbSXeSxxvs1voWR-0](fqR0EHi63lWahRcVTKCcba-fi-3472%3A185864)

### Acceptance criteria - Backend

- [X] Endpoint to fetch  "Final URLs" from post/product/terms pages. https://github.com/woocommerce/google-listings-and-ads/pull/1784
- [x] Endpoint to fetch assets from specific URL. 
  * [x] Fetch assets for Posts. https://github.com/woocommerce/google-listings-and-ads/pull/1795
    * [x] Suggest inserted HTML Images https://github.com/woocommerce/google-listings-and-ads/pull/1860
  * [x] Fetch assets for Terms. https://github.com/woocommerce/google-listings-and-ads/pull/1797
- [x] Resize images https://github.com/woocommerce/google-listings-and-ads/pull/1804
- [x] Endpoint to fetch AssetGroup and Assets using the Ads API. https://github.com/woocommerce/google-listings-and-ads/pull/1820
- [x] Endpoint to update AssetGroups.  https://github.com/woocommerce/google-listings-and-ads/pull/1832
- [x] Fetch assets from others asset groups. https://github.com/woocommerce/google-listings-and-ads/pull/1837
- [x] Add default assets for a non-static homepage.  https://github.com/woocommerce/google-listings-and-ads/pull/1847
- [x] Endpoint to create AssetGroups https://github.com/woocommerce/google-listings-and-ads/pull/1851
- [x] Assets batching - https://github.com/woocommerce/google-listings-and-ads/pull/1864
- [x] Add Marketing Portrait images - https://github.com/woocommerce/google-listings-and-ads/pull/1868
- [x] Override Landscape Logo - https://github.com/woocommerce/google-listings-and-ads/pull/1869
- [x] Update Google Ads from v11 to v12. - https://github.com/woocommerce/google-listings-and-ads/pull/1896
