### ISSUE TITLE
PMax Assets - Stage 1

### ISSUE THREAD

**Issue by eason9487** [woocommerce/google-listings-and-ads#1787]
## Technical Goals

- Enable merchants to launch PMax campaigns based on their assets.
- Enable merchants to maintain their assets of PMax campaigns.

## Terminology

- **PMax**: Performance Max
   - https://www.google.com/retail/solutions/performance-max/
   - https://support.google.com/google-ads/answer/10724817
- **Assets**: PMax campaigns have some unique characteristics regarding assets.
   - Assets are grouped together in a collection called an AssetGroup, which is unique to PMax campaigns.
- **AssetGroup**: An AssetGroup is made from the images, logos, headlines, descriptions, etc when creating a PMax campaign.
   - Google Ads automatically mixes and matches these assets based on which Google Ad channel (YouTube, Gmail, Search, etc.) the ad is being served.
- **Final URL**: The page URL on merchant's website that people reach when they click Google's ad.
   - A page URL is required when creating an asset group.
   - On WooCommerce side, it refers to a post, page or taxonomy

## <a href="#tech-frontend" id="tech-frontend">Technical - Frontend</a>

The main scope is the campaign management page and the Dashboard page.

### 📌 <a href="#fe-campaign-step2" id="fe-campaign-step2">Add step 2 to the campaign management page</a>

- [x] Creation page [#1794](https://github.com/woocommerce/google-listings-and-ads/pull/1794)
- [x] Editing page [#1799](https://github.com/woocommerce/google-listings-and-ads/pull/1799)
- [x] The routing of editing page can direct to step 2 [#1799](https://github.com/woocommerce/google-listings-and-ads/pull/1799)
- [x] Add FAQs [#1881](https://github.com/woocommerce/google-listings-and-ads/pull/1881)
- [x] Add a basic section for placing the assets form [#1794](https://github.com/woocommerce/google-listings-and-ads/pull/1794)
- [x] Adjust the buttons in the footer for each step [#1794](https://github.com/woocommerce/google-listings-and-ads/pull/1794)

### 📌 <a href="#fe-misc" id="fe-misc">Assets form and related components</a>

- [x] Card for the Final URL [#1805](https://github.com/woocommerce/google-listings-and-ads/pull/1805)
   - [x] Input field for searching pages ([WC SelectControl](https://github.com/woocommerce/woocommerce/tree/6.9.0/packages/js/components/src/select-control)) [#1805](https://github.com/woocommerce/google-listings-and-ads/pull/1805)
   - [x] Button for loading assets [#1805](https://github.com/woocommerce/google-listings-and-ads/pull/1805)
   - [x] Button for selecting another page [#1805](https://github.com/woocommerce/google-listings-and-ads/pull/1805)
   - [x] The Final URL of the non-empty asset group is not allowed to change [#1874](https://github.com/woocommerce/google-listings-and-ads/pull/1874)
- [x] New component to construct the layout and the common parts for editing images and texts [#1853](https://github.com/woocommerce/google-listings-and-ads/pull/1853)
- [x] Multiple images selector [#1819](https://github.com/woocommerce/google-listings-and-ads/pull/1819)
   - Medial Modal library:
      - https://codex.wordpress.org/Javascript_Reference/wp.media
      - https://github.com/WordPress/wordpress-develop/blob/5.9.0/src/js/_enqueues/wp/media/models.js
      - https://github.com/woocommerce/woocommerce/blob/6.9.0/packages/js/components/src/image-upload/index.js
- [x] Multiple texts editor [#1854](https://github.com/woocommerce/google-listings-and-ads/pull/1854)
    - [x] Characters length calculation [#1854](https://github.com/woocommerce/google-listings-and-ads/pull/1854)
- [x] Assets form [#1862](https://github.com/woocommerce/google-listings-and-ads/pull/1862) [#1863](https://github.com/woocommerce/google-listings-and-ads/pull/1863)
   - [x] Validate asset group and show error messages [#1863](https://github.com/woocommerce/google-listings-and-ads/pull/1863)
   - [x] Scroll to the error asset field which is nearest the top of page [#1863](https://github.com/woocommerce/google-listings-and-ads/pull/1863)
   - [x] Support the portrait marketing image and adjust the maximum limits of each marketing image type [#1873](https://github.com/woocommerce/google-listings-and-ads/pull/1873)
   - [x] Change the implementation to share the maximum number of image assets across all types of marketing image assets [#1894](https://github.com/woocommerce/google-listings-and-ads/pull/1894)
- [x] Align with the finalized copy and add the optional labels [#1882](https://github.com/woocommerce/google-listings-and-ads/pull/1882)

### 📌 <a href="#fe-dashboard-programs" id="fe-dashboard-programs">Programs table on the Dashboard page</a>

- [x] Add a tour to the Dashboard page for introducing this new feature. [#1880](https://github.com/woocommerce/google-listings-and-ads/pull/1880)

### 📌 <a href="#fe-integrating-apis" id="fe-integrating-apis">Integrating with backend APIs</a>

- [x] Query website pages by page title [#1805](https://github.com/woocommerce/google-listings-and-ads/pull/1805)
- [x] Load suggested assets by a page [#1805](https://github.com/woocommerce/google-listings-and-ads/pull/1805)
- [x] Preprocessing for API integration [#1872](https://github.com/woocommerce/google-listings-and-ads/pull/1872)
- [x] Load existing asset groups or suggested assets [#1874](https://github.com/woocommerce/google-listings-and-ads/pull/1874)
- [x] When creating a new campaign, update the assets into the empty asset group of the newly created campaign [#1874](https://github.com/woocommerce/google-listings-and-ads/pull/1874)
- [x] When editing a campaign, create an asset group if needed, and update the assets into the existing or newly created asset group [#1874](https://github.com/woocommerce/google-listings-and-ads/pull/1874)
- [x] Re-order the strings for the headline and description assets to prevent the first string from exceeding the smaller limit [#1899](https://github.com/woocommerce/google-listings-and-ads/pull/1899)

### 📌 <a href="#fe-event-tracking" id="fe-event-tracking">Event tracking</a>

- [x] Add event tracking [#1884](https://github.com/woocommerce/google-listings-and-ads/pull/1884)

![2023-02-14 15 03 24](https://user-images.githubusercontent.com/17420811/218664366-f8d140b6-f2bb-4e38-b6b8-f16d146748f2.png)
![2023-02-14 15 04 36](https://user-images.githubusercontent.com/17420811/218664379-156e793c-42cc-4a8a-9a66-55cd0051e5f4.png)
![2023-02-14 15 05 15](https://user-images.githubusercontent.com/17420811/218664386-8787a028-3dfe-4d89-a3b3-16b700287583.png)

- **A**: `gla_import_assets_by_final_url_button_click` with a property.
   - `type`: post | term | homepage
- **B**: `gla_reselect_another_final_url_button_click`
- **C** and **D**: `gla_submit_campaign_button_click` with some properties.
   - `context`: campaign-creation | campaign-editing
   - `action`: submit-campaign-and-assets | submit-campaign-only
   - `audiences`: country codes like `US,JP,AU`
   - `budget` budget of the campaign
   - `assets_validation`: valid | invalid | unknown
   - `number_of_business_name`: number of this asset in string type | unknown
   - `number_of_marketing_image`
   - `number_of_square_marketing_image`
   - `number_of_portrait_marketing_image`
   - `number_of_logo`
   - `number_of_headline`
   - `number_of_long_headline`
   - `number_of_description`
   - `number_of_call_to_action_selection`
   - `number_of_final_url`
   - `number_of_display_url_path`
   - (The possible values of all number_of_[asset_key] are the same as the `number_of_business_name`)

### 📌 <a href="#fe-tests" id="fe-tests">Add tests</a>

- [ ] The additional enhancements in `AdaptiveForm`
- [x] `ImagesSelector` component [#1862](https://github.com/woocommerce/google-listings-and-ads/pull/1862)
- [x] The functions in the `useCroppedImageSelector` hook [#1862](https://github.com/woocommerce/google-listings-and-ads/pull/1862)
- [ ] The `eventProps` in the `recordSubmissionClickEvent` function

## Technical - Backend

Please refer to #1780

### Project: 

- Project thread: pcTzPl-12o-p2
- Design thread: pcTzPl-1eS-p2

### Figma: 

- i2 final: fqR0EHi63lWahRcVTKCcba-fi-5299%3A224024 ⬅️
- i2: fqR0EHi63lWahRcVTKCcba-fi-3762%3A215599
