### ISSUE TITLE
Gradually externalize `@wordpress/components` and finally opt-in all imports via DEWP

### ISSUE THREAD

**Issue by eason9487** [woocommerce/google-listings-and-ads#1833]
With the ability to selectively externalize specific imports, introduced in #1762, we can start gradually externalizing `@wordpress/components`, and finally opt-in all imports via DEWP.

This issue is used to track this process and illustrate the approach.

## Progress of `@wordpress/components` imports to be externalized

- [x] __experimentalInputControl - [#2054](https://github.com/woocommerce/google-listings-and-ads/pull/2054)
- [x] Button - [#1834](https://github.com/woocommerce/google-listings-and-ads/pull/1834)
   - `@import "node_modules/@wordpress/components/src/button/style";` in *_gutenberg-components.scss* should be removed together.
- [x] Card - [#2036](https://github.com/woocommerce/google-listings-and-ads/pull/2036)
- [x] CardBody - [#2036](https://github.com/woocommerce/google-listings-and-ads/pull/2036)
- [x] CardDivider - [#2036](https://github.com/woocommerce/google-listings-and-ads/pull/2036)
- [x] CardFooter - [#2036](https://github.com/woocommerce/google-listings-and-ads/pull/2036)
- [x] CardHeader - [#2036](https://github.com/woocommerce/google-listings-and-ads/pull/2036)
- [x] CheckboxControl - [#2054](https://github.com/woocommerce/google-listings-and-ads/pull/2054)
- [x] Dashicon - [#2037](https://github.com/woocommerce/google-listings-and-ads/pull/2037)
- [x] Dropdown - [#2042](https://github.com/woocommerce/google-listings-and-ads/pull/2042)
- [x] ExternalLink
- [x] Flex - [#2036](https://github.com/woocommerce/google-listings-and-ads/pull/2036)
- [x] FlexBlock - [#2036](https://github.com/woocommerce/google-listings-and-ads/pull/2036)
- [x] FlexItem - [#2036](https://github.com/woocommerce/google-listings-and-ads/pull/2036)
- [x] Icon - [#2037](https://github.com/woocommerce/google-listings-and-ads/pull/2037)
- [x] KeyboardShortcuts - [#1914](https://github.com/woocommerce/google-listings-and-ads/pull/1914)
- [x] Modal - [#2042](https://github.com/woocommerce/google-listings-and-ads/pull/2042)
- [x] NavigableMenu - [#2042](https://github.com/woocommerce/google-listings-and-ads/pull/2042)
- [x] Notice - [#2037](https://github.com/woocommerce/google-listings-and-ads/pull/2037)
- [x] Panel - [#1881](https://github.com/woocommerce/google-listings-and-ads/pull/1881)
   - `@import "node_modules/@wordpress/components/src/panel/style";` in *_gutenberg-components.scss* should be removed 
- [x] PanelBody - [#1881](https://github.com/woocommerce/google-listings-and-ads/pull/1881)
- [x] PanelRow - [#1881](https://github.com/woocommerce/google-listings-and-ads/pull/1881)
- [x] Popover
- [x] RadioControl - [#2054](https://github.com/woocommerce/google-listings-and-ads/pull/2054)
- [x] SelectControl - [#2054](https://github.com/woocommerce/google-listings-and-ads/pull/2054)
- [x] Tip - [#2037](https://github.com/woocommerce/google-listings-and-ads/pull/2037)
- [x] ToggleControl - [#2054](https://github.com/woocommerce/google-listings-and-ads/pull/2054)
- [x] Tooltip

### Externalization steps

1. Add `'extracted/'` prefix to all `'@wordpress/components'` imports of the selected component(s).
   - For example, `import { Modal } from '@wordpress/components';` should be changed to `import { Modal } from 'extracted/@wordpress/components';`.
   - Please note that components with dependencies should be externalized together, e.g. `Flex`, `FlexBlock` and `FlexItem`.
1. Search if there are related JavaScript workarounds for compatibility reasons that can be removed as well.
1. Search if there are related CSS styles for compatibility reasons that can be removed as well.
   - If these CSS styles still need to be preserved, check whether they can be scoped to the CSS class `.gla-admin-page` in *_gutenberg-components.scss*.
1. Test the usages of the externalized components in GAL with WordPress versions covering at least L-2.
1. Once a PR has been merged, please mark the related tracking item(s) as completed in this issue.

## Opt-in all `@wordpress/components` imports via DEWP

Once all the externalizations are done, it should be time to opt-in `@wordpress/components` via DEWP and revert all related imports back to without the `extracted/` prefix

- [x] Remove `'extracted/'` prefix from all `'extracted/@wordpress/components'` imports - [#2055](https://github.com/woocommerce/google-listings-and-ads/pull/2055)
- [x] Remove `@import "node_modules/@wordpress/components/src/date-time/date/datepicker";` from *_gutenberg-components.scss* - [#2055](https://github.com/woocommerce/google-listings-and-ads/pull/2055)
- [x] Remove `'@wordpress/components'` from the `requestToExternal` array in the webpack config - [#2055](https://github.com/woocommerce/google-listings-and-ads/pull/2055)

## Reference

- [Working with DEWP](https://github.com/woocommerce/google-listings-and-ads/blob/develop/Working%20with%20DEWP.md)
- #1762
- #1844
- https://github.com/woocommerce/google-listings-and-ads/pull/1834#pullrequestreview-1237134352
- https://github.com/woocommerce/google-listings-and-ads/pull/1834#pullrequestreview-1238525699
