### ISSUE TITLE
64 bit PHP as a prerequisite

### ISSUE THREAD

**Issue by mikkamp** [woocommerce/google-listings-and-ads#1849]
## User story
Google Merchant Center is moving it's account ID's to 64 bit (signed) integers, which means we'll have to support any account ID's larger than 32 bit. In the extension we handle all account ID's as the type `int`. As long as a 64 bit PHP version is installed that means an int is a signed 64 bit integer.

Since 64 bit is the norm, we want to add it as a pre-requisite to run the extension. Similar to how we require at least PHP 7.4.
We can use `PHP_INT_SIZE` to determine whether it's a 64 bit version or not.

### Tasks
- [x] Add a requirement check for 64 bit PHP
- [x] Add the requirement to readme.txt, README.md and any other documentation where prerequisites/minimum requirements are mentioned
- [x] Add the requirement to the public documentation: https://woocommerce.com/document/google-listings-and-ads/

### Project details
pcTzPl-1jE-p2

**Comment by strarsis** [comment]
@mikkamp: Will existing plugins automatically update the existing merchant ID to 64bit, or is a re-authorization/re-connection necessary?

**Comment by mikkamp** [comment]
@strarsis Any existing Merchant ID's will not change and do not need any to perform any actions. This change will affect newer accounts that are created after March, where Google will start giving out ID numbers which are larger than 32 bit numbers.

As long as you are running the extension in a 64 bit version of PHP then it was already capable of storing these larger ID numbers so no changes are needed.
