### ISSUE TITLE
Improve the error handling and prompts in the onboarding

### ISSUE THREAD

**Issue by eason9487** [woocommerce/google-listings-and-ads#1993]
## Goals

During the onboarding

- Prompts for explicit errors such as incorrect input formatting or missing required fields to reduce confusion for users
- Make error messages more specific as to which part of the error occurred

The main scope is the Onboarding flow and the Edit Free Listings page. (The editing page basically reuses most of the code)

### 📌 <a href="#tasks-error-handling" id="tasks-error-handling">Deal with technical error handling</a>

```[tasklist]
- [x] https://github.com/woocommerce/google-listings-and-ads/issues/489
- [x] https://github.com/woocommerce/google-listings-and-ads/issues/1331
- [x] https://github.com/woocommerce/google-listings-and-ads/issues/1246
```

These tasks are more about technical adjustments. It expects to use the current UI and will not change significantly.

### 📌 <a href="#tasks-display-validation-errors" id="tasks-display-validation-errors">Display form validation errors</a>

```[tasklist]
- [x] https://github.com/woocommerce/google-listings-and-ads/issues/634
```

This is the top priority in this project as there were a lot of user reports related to it.

To display the form/data validation errors, the main points of the change are:

1. Change the timing of triggering form validation and showing errors.
   - Don't disable the "Continue" or "Compete" buttons even if the form validation doesn't pass.
   - The form validation errors are not displayed until the user clicks the above button.
   - After displaying the validation errors, the errors will continue to be updated with user input.
2. Similar to the Asset Group management page. The error messages are grouped by `Card` UI and are displayed below the UI layout they belong to.
   - For example:
      ![image](https://github.com/woocommerce/google-listings-and-ads/assets/17420811/854af97f-047f-46d8-b65c-d0cf6263dfdc)
3. The # issues pill UI won't be added because the forms other than Asset Group don't have the collapse and expanding interaction.
4. These changes won't be applied to the modals of shipping setup as the modal should be clear enough and no user seems to have reported a problem with this.
   - Shipping modal:
      ![image](https://github.com/woocommerce/google-listings-and-ads/assets/17420811/2df5c4d5-7d33-4095-aea4-3229f3073ffb)
5. To be consistent, the event tracking of the above buttons will still be triggered only when the step can be proceeded to the next one or be completed.

### 📌 <a href="#tasks-clarify-api-errors" id="tasks-clarify-api-errors">Clarify API error messages</a>

```[tasklist]
- [x] https://github.com/woocommerce/google-listings-and-ads/issues/1725
- [x] https://github.com/woocommerce/google-listings-and-ads/issues/1855
- [x] https://github.com/woocommerce/google-listings-and-ads/issues/1101
```

The error messages in these tasks were already handled or shown but may confuse users. It expects to use the current UI or remove the unnecessary error message.

### 📌 <a href="#fe-tests" id="fe-tests">Add tests</a>

- [x] Add tests for the `VerifyPhoneNumberContent` component ([#2027](https://github.com/woocommerce/google-listings-and-ads/pull/2027), [#2031](https://github.com/woocommerce/google-listings-and-ads/pull/2031))

### Project: 

- Project thread: pcTzPl-1yj-p2

**Comment by eason9487** [comment]
Close this issue: All listed tasks have been completed.
