### ISSUE TITLE
Authentication: Google Account Connection

### ISSUE THREAD

**Issue by findingsimple** [woocommerce/google-listings-and-ads#2]
**User story:**

As a merchant
I want to connect my store to my Google account
So that I can use Google features

**Description:**

In order to communicate with Google services via Google APIs applications [must use OAuth 2.0 to authorize requests](https://developers.google.com/shopping-content/guides/how-tos/authorizing).

**Screenshots**

![Screen Shot 2020-11-03 at 3 46 04 pm](https://user-images.githubusercontent.com/355014/97951948-bcfab880-1deb-11eb-919c-72550d556abc.png)

![Screen Shot 2020-11-03 at 3 46 58 pm](https://user-images.githubusercontent.com/355014/97951987-e3205880-1deb-11eb-8d03-469dc70cdd98.png)

Snackbar notice

![Screen Shot 2020-11-03 at 4 21 40 pm](https://user-images.githubusercontent.com/355014/97953526-b28eed80-1df0-11eb-904e-6745982859ca.png)

**Technical:**

* Requires WordPress.com connection
* Button component
* Snackbar notice component
* In OAuth request, Google recommended ensuring we have set the access_type to offline because “you can refresh an access token without prompting the user for permission (including when the user is not present) if you requested offline access to the scopes associated with the token.” - basically means the “refresh_token” is returned.

**Acceptance criteria:**

* [x] Merchant can choose to connect an existing account
* [x] Merchant can choose to disconnect their account
* [x] Button color updates to reflect admin profile color scheme
* [ ] Tracks event fired
* [x] Translatable text
* [ ] Snackbar notice displayed
* [x] Correct permissions/scopes are requested

**Out of bounds/rabbit holes**

*  TBD

**Dependencies**

* [Full screen set up screen/page](https://github.com/woocommerce/google-for-woocommerce/issues/44)
* [WordPress.com Connection](https://github.com/woocommerce/google-for-woocommerce/issues/1)

**Event tracking:**

* [ ] Track whether an existing account is used or whether one is created
* [ ] Track connects
* [ ] Track disconnects
