### ISSUE TITLE
Google Ads Account

### ISSUE THREAD

**Issue by findingsimple** [woocommerce/google-listings-and-ads#20]
**User story:**

As a merchant
I want to connect my Merchant Center account to my Google Ads account
So that I can easily enable my Google **paid** listings

**Description:**

To create/use paid listings, Merchant will need to connect a Google Ads account.

**Acceptance criteria:**

* [x] Merchant must accept Google’s ToS so that they can use Google's Services **(new accounts only)**
* [x] Acceptance of ToS are stored for future reference with a timestamp indicating when the terms were accepted.
* [x] ~The ToS are country-specific. Show the merchant the correct Terms of Service based on where their business is physically located.~ The ToD are country-specific but we can simply link to the Google documentation which specifies them all.
* [x] Merchant can choose to connect to an existing Google Ads account
* [x] Merchant can choose to create a new Google Ads account
* [x] Prompt merchant to add billing information to Google Ads (needs to go via Google Ads)

**Dependencies**

* Google Account Connection

**Event tracking:**

TBD
