### ISSUE TITLE
External wc-admin/components work/questions

### ISSUE THREAD

**Issue by jconroy** [woocommerce/google-listings-and-ads#201]
This is purely a running collection of open questions and changes/adjustments to wc-admin (or wp components) we need to look at relevant for the project.

(Feel free to update - if we really need stuff we'll need help make it happen)

[Marketing labeled issues](https://github.com/woocommerce/woocommerce-admin/issues?q=is%3Aissue+is%3Aopen+label%3A%22feature%3A+marketing%22)

## [wc-admin](https://github.com/woocommerce/woocommerce-admin/issues/)
 - [ ] New recommended way to fetch WC Admin settings - https://github.com/woocommerce/woocommerce-admin/issues/7802
### `woocommerce/components`
 - [ ] Could Report* components be added to components package? https://github.com/woocommerce/woocommerce-admin/issues/6243
 - [x] wcadmin_analytics_filter events' value inconsistency https://github.com/woocommerce/woocommerce-admin/issues/6237
 - [x] wcadmin_analytics_filter Tracking event is blind to variation filter changes. https://github.com/woocommerce/woocommerce-admin/issues/6221
 - [ ] @woocommerce/components dependency breaks tests for external plugins https://github.com/woocommerce/woocommerce-admin/issues/6483
 - [x] `FilterPicker` does not forward all props to `Search` component https://github.com/woocommerce/woocommerce-admin/issues/6062
 - [x] `CompareFilter` does not forward `autocompleter` setting to the `Search` https://github.com/woocommerce/woocommerce-admin/issues/6890
 - [x] Search component does not accept static options Array in autocomplete https://github.com/woocommerce/woocommerce-admin/issues/6061
 - [x] We workaround `Chart` to hide the legend, by setting `legendPosition: 'hidden'`. We should secure that as a feature. https://github.com/woocommerce/google-listings-and-ads/issues/618
 - [ ] WC`<Link type="external">` is inconsistent with WP `<ExternalLink>` https://github.com/woocommerce/woocommerce-admin/issues/7614
 
 ## [Woo](https://github.com/woocommerce/woocommerce/issues/)
 ### `@woocommerce/e2e-utils`
 - [ ] test example/ mock for Jetpack connection https://github.com/woocommerce/woocommerce/issues/25741
 	Required to make e2e test for GLA onboarding.
 ### `@woocommerce/e2e-environment`
 - [ ] Log WC version number when running wc-e2e docker:up https://github.com/woocommerce/woocommerce/issues/30687
 	Usefull for testing against multiple versions, checking compatibility, etc.

**Comment by tomalec** [comment]
@jconroy I wonder whether it's much value with tracking here all those issues. Given our sweet dependency hell (pb0Spc-1LK-p2), AKA:
- we support a range of WP & WC versions
- which comes with a range of individual versions
- we don't know which versions are delivered with WC
- sometimes it's not even a released version, but a specific commit from branch https://github.com/woocommerce/woocommerce-admin/issues/7628

the fact that the upstream issue was solved is far from making a change for us.

Also, as the external repose does not mention in which version the PR will be released it requires even more manual scavenging whether we can remove our workaround or not.

**Comment by tomalec** [comment]
I'm closing the issue, as I believe all the external issues are covered/ worked around to a sufficient extent.

I believe for any future issue, we can create an issue in an external repo, then add a link in a code comment in our code-base, close to the workaround, so it could be easily revisited later and removed if no longer needed.
