### ISSUE TITLE
Add additional E2E tests

### ISSUE THREAD

**Issue by ianlin** [woocommerce/google-listings-and-ads#2070]
(co-author: @jorgemd24)

Project: pcTzPl-1Kl-p2

## Goals

To reduce the amount of [manual smoke tests](<https://github.com/woocommerce/google-listings-and-ads/wiki/Smoke-tests>) we need to run for compatibility testing.

So far the E2E test covers the first step of onboarding and connecting / disconnecting both a WordPress and a Google account. We can start by adding the test to connect to Merchant Account and then move on to the next steps of onboarding.

For testing the main page we can follow the list from [manual smoke tests](<https://github.com/woocommerce/google-listings-and-ads/wiki/Smoke-tests>).

## Tests to add

We will assign priorities to the tasks below:

🔴 means high priority<br>🟢 means low priority

### 📌 [Onboarding Step 1 - Set up accounts](<#onboarding-step-1>)

```[tasklist]
- [x] 🔴 Connecting an existing Merchant Account (including all the steps such as claiming / overriding a URL etc).
- [x] 🔴 Create a new Merchant Account.
- [x] 🟢 Verify FAQ can expand.
- [x] 🟢 Verify the links on the page can be clicked and can open the correct page.
```

### 📌 [Onboarding Step 2 - Configure product listings](<#onboarding-step-2>)

```[tasklist]
- [x] 🔴 The default language is preselected
- [x] 🔴 Select countries US and UK and both countries will appear in the country select box
- [x] 🔴 Checking the "All countries" option hides the country select textbox
- [x] 🔴 If US is not selected, the card `Tax rate (required for U.S. only)` at the bottom is not displayed.
- [x] 🔴 Test when "My shipping settings are simple”
- [x] 🔴 Test when "My shipping settings are complex”
- [x] 🔴 Test "Recommended” shipping rates
- [x] 🟢 The "Continue" button is disabled if no shipping time is entered on a simple shipping setup
- [x] 🟢 The headings `Configure your product listings` etc are shown
- [x] 🟢 Verify the links on the page can be clicked and can open the correct page.`
```

### 📌 [Onboarding Step 3 - Confirm store requirements](<#onboarding-step-3>)

```[tasklist]
- [x] 🟢 Phone verification
- [x] 🟢 Pre-Launch Checklist
- [x] 🟢 The "Continue" button is disabled until the Pre-Launch Checklist is checked and the Store address is valid
- [x] 🟢 Confirm links, copies, etc are shown in the UI
```

### 📌 [Onboarding Step 4 - Complete your campaign](<#onboarding-step-4>)

```[tasklist]
- [x] 🔴 Clicking on "Create a paid ad campaign" can show Google Ads, Ads audience, and Set your budget sections; The audience and budget sections should be shown in disabled
- [x] 🔴 Connect an existing Ads account to add a paid campaign and ensure the journey works. (Could share some code with the test in Dashboard for creating a paid campaign)
- [x] 🔴 Click “Skip this step for now” will go to Product Feed page, and the submission success guide will pop up.
- [x] 🟢 Confirm links, copies, and number of syncable products, etc are shown in the UI
```

### 📌 [Google Listings & Ads - Dashboard](<#gla-dashboard>)

```[tasklist]
- [x] 🔴 Edit free listings and make sure it can save successfully.
- [x] 🔴 Create a campaign by clicking the "Add paid campaign" button and ensure the journey works.
- [ ] 🟢 Disable a campaign from the "Programs" table and ensure the campaign has been paused in Google ads
- [ ] 🟢 Remove a campaign from the "Programs" table and ensure the campaign has been removed in Google ads.
```

### 📌 [Google Listings & Ads - Reports](<#gla-reports>)

```[tasklist]
- [ ] 🟢 Programs tab - Click on Single Program (Maybe mock the report data?)
- [ ] 🟢 Programs tab - Click on Comparison
- [ ] 🟢 Products tab - Click on Single Product
- [ ] 🟢 Products tab - Click on Comparison
```

### 📌 [Google Listings & Ads - Product Feed](<#gla-product-feed>)

```[tasklist]
- [ ] 🔴 Select a product in the "Product Feed" table and update the channel visibility
- [ ] 🟢 Click on the pagination link on the Product table to ensure this works
- [ ] 🟢 Click on the pagination link on the "Issues to resolve" table to ensure this works
```

### 📌 [Google Listings & Ads - Settings](<#gla-settings>)

```[tasklist]
- [ ] 🔴 Disconnect all google accounts.
- [ ] 🟢 Disconnect Google Ads only
```

### 📌 [Google Listings & Ads - Product Sync](<#gla-product-sync>)

```[tasklist]
- [ ] 🟢 Click Sync All Products (test that the button issues the correct request?)
- [ ] 🟢 Click Delete All Synced Products
```
