### ISSUE TITLE
Google API Project

### ISSUE THREAD

**Issue by jorgemd24** [woocommerce/google-listings-and-ads#2146]
## User story

The full details of the project can be found in the following links:

pbIy4N-3Lx-p2  <br>pcTzPl-1PW-p2<br>pcTzPl-1PW-p2

## Shared branch for development

[feature/google-api-project](<https://github.com/woocommerce/google-listings-and-ads/tree/feature/google-api-project>)

### WPCOM - GLA

- [X] Allow to connect WPCOM App without Jetpack (the plugin) **Stage 1**
- [ ] Once `automattic/jetpack-connection` is updated and includes all the functions required to connect the WPCOM App, update the package and remove the duplicated code from the previous step. \*\* This is depending on Jetpack \*\*
- [X] Add WC REST API filters to transform the data before sending the response.  **Stage 1**
- [X] Restrict API access if the channel visibility is `dont-sync-and-show`, for products and coupons. **Stage 1**
- [X] Restrict API access if coupons are allowed for specific emails. **Stage 1**
- [X] Expose Attribute values. **Stage 1**
- [X] Expose `gla_target_audience` option in `wc/v3/settings/general` **Stage 1**
- [X] Expose shipping and the rest of the onboarding data in `wc/v3/settings/general` **Stage 1**
- [X] Expose `offer_id` in deleting notification products.
- [X] Add Endpoint to get partner integration status  **Stage 1**
- [X] Add Endpoint to revoke WPCOM access  **Stage 1**
- [X] Add Event tracking (`gla_enable_product_sync_click` & `gla_disable_product_sync_click`) **Stage 1** - [#2424](<https://github.com/woocommerce/google-listings-and-ads/issues/2424>)

### Granting/Onboarding flow.

- [X] Decide the onboarding flow for the new connections. **Stage 1**
- [X] Create Auth URL **Stage 1**
- [X] Grant Access to the App in the Settings Page  **Stage 1**
- [X] Add a section to the Connection Test page to retrieve the integration status. **Stage 1**
- [X] Add a section to the Connection Test page to revoke the WPCOM access. **Stage 1**

### Notifications

- [X] Notify Google when a product is created/updated/deleted. **Stage 1**
- [X]  Notify Google when a coupon is created/updated/deleted. **Stage 1**
- [X]  Notify Google when a shipping zone is created/updated/deleted. **Stage 1**
- [X] Validate merchant center setup when triggering notifications **Stage 1**

### Migration

- [X] Research which elements of the UI need to be updated. **Stage 1**
- [X] Update mechanism to pull the Product Overview  **Stage 1**
- [X] Update mechanism to pull the Product issues  **Stage 1**
- [X] Show a banner to indicate the current status of the connection. See here: pcTzPl-1QJ-p2 (in-progress) \*\*Stage 1 \*\*Stage 1 \*\*\*\*
- [X] Block current MC Sync for Products and Copuons when WPCOM is granted. **Stage 1** [https://github.com/woocommerce/google-listings-and-ads/pull/2326](<https://github.com/woocommerce/google-listings-and-ads/pull/2326>)
- [X] Handle Coupon sync status **Stage 1**
- [ ] Clear products stats cache when  any Product Notification is sent **Stage 2**

### Monitor/Health

- [X] Add an endpoint to query the WC REST API current status. **Stage 1**

#### First Stage: Provide merchants with the option to use the new sync method.

- [X] Keep the code for both the pull and push mechanisms at this point, as existing users will continue to utilize the push mechanism. **Stage 1**

#### Second Stage: All merchants should be using the new mechanism.

- [ ] Remove product syncing code. **Final stage**
- [ ] Remove coupon syncing code. **Final stage**
- [ ] Remove shipping syncing code. **Final stage**
- [ ] Revisist Multichannel Sync stats logic to use `update_merchant_product_statuses` **Final stage**
- [ ] Remove ProductMetaHandler::KEY_SYNC_STATUS since it will no longer serve any purpose. **Final stage**
