### ISSUE TITLE
[R-1] Enable users to seamlessly setup conversion tracking, without requiring merchant center setup or campaign creation

### ISSUE THREAD

**Issue by sstopfer** [woocommerce/google-listings-and-ads#2215]
# Overview 

The goal of this requirement is to move the Google Ads Account Connection process from Step 4 to Step 1 of the onboarding workflow, as a required step above the Merchant Center account setup so that conversion tracking can be set up without requiring a Merchant Center connection.

Design Reference: [Figma Link](https://www.figma.com/file/fODAWLBsbvd2MVmdh1Hgk3/Google-Listings-%26-Ads---Alternative-Conversion-Tracking-Flow?type=design&node-id=616-11376&mode=design&t=04zEOEnkTYBWOUia-0)

## Requirements Breakdown

- [ ] Add Google Ads Account Connection to Step 1 of the Onboarding flow
- [ ] Update Step 4 of the Onboarding flow

### Add Google Ads Account Connection to Step 1 of the Onboarding flow

PR: [Allow conversion tracking without merchant account](https://github.com/woocommerce/google-listings-and-ads/pull/2205)

- Add the Google Ads Account Connection Module from Step 4 to Step 1 of onboarding flow (this will also trigger ads conversion tracking setup)
  - Google Ads Account Connection Module should be above the Google Merchant Center Connection Module 
  - Google Ads Account setup should be required in this step; i.e., users should not be able to move forwards in the onboarding flow without setting up a Google Ads account (or other accounts connected in this page)  
  - If users set up Google Ads first, then the link between Merchant Center and Google Ads should happen upon MC creation. 
- Enable Ads Conversion Tracking Setup Upon Ads Account Creation (previously upon “Complete Setup” after billing & campaign creation)
- Users should be able to clearly understand what each step is doing and what is required depending on their journey (i.e., conversion tracking setup only, full ads setup, free listings only) 
  - Google Ads: “Required to set up conversion measurement and create campaigns. You can also create or connect an account later.”
  - Google Merchant Center: Required to sync products and list on Google 
- Once the Google ads account is created and connected and conversion tracking is enabled, the user should be informed of that state. Users who would like to set up Conversion Tracking only would stop at this step  
- E2E tests
  - Update or add E2E tests in tests/e2e/specs/setup-mc/
  - Fix existing  E2E test if failing
- Add backward compatibility if needed. This change should not break existing functionality. 

### Update Step 4 of the Onboarding flow

- Implement copy changes to step title, subtitle, ads benefits card, and sidebars as listed in the [Figma](https://www.figma.com/file/fODAWLBsbvd2MVmdh1Hgk3/Google-Listings-%26-Ads---Alternative-Conversion-Tracking-Flow?type=design&node-id=616-11376&mode=design&t=bIsFdqe2i9xl5SBA-0)
- Remove product sync completion card 
- Since the user has already connected an ads account in Step 1:
  - Remove the Google Ads Account Connection Module from step 4
  - Campaign setup steps should be shown by default
  - The user will still be given an option at the bottom of the page to “Skip Campaign Setup, for now
- E2E tests
  - Update or add E2E tests in tests/e2e/specs/setup-mc/
  - Fix existing  E2E test if failing
- Add backward compatibility if needed. This change should not break existing functionality.
```[tasklist]
### Sub-tasks
- [ ] https://github.com/woocommerce/google-listings-and-ads/issues/2262
- [ ] https://github.com/woocommerce/google-listings-and-ads/pull/2308
```
