### ISSUE TITLE
Enable Enhanced Conversions (EC) for GL&A

### ISSUE THREAD

**Issue by sstopfer** [woocommerce/google-listings-and-ads#2216]
# Overview 

This is a tracking issue for enabling Enhanced Conversions in the plugin.

The goal of this requirement is to allow users the option to configure [Enhanced Conversions](https://support.google.com/google-ads/answer/9888656?hl=en), through Google Listings & Ads in order to improve performance of existing conversion measurement, by supplementing conversion tags with first party customer data in a privacy safe way. 

Developer Documentation: https://developers.google.com/google-ads/api/docs/conversions/enhanced-conversions/web

### R 2.1 – Develop post-onboarding pop-up modal panel to configure enhanced conversions

![Success Modal](https://github.com/woocommerce/google-listings-and-ads/assets/801097/e6bd3261-06f3-4c46-940d-27845bbc5f54)

- [x] [#2239 Add a page to the `SubmissionSuccessGuide` panel to enable Enhanced Conversions](https://github.com/woocommerce/google-listings-and-ads/issues/2239)
- [x] Develop a REST API endpoint for reading ToS status (via #2242) 
- [x] Develop a REST API endpoint for reading/writing ToS Enhanced Conversions status (via #2242)
- [x] Integrate REST API endpoints with the success modal EC page (via #2242)
- [x] Update gtag and purchase conversions when EC is enabled (via #2258)

### R 2.2 – Develop a panel in the Google Listings & Ads Settings Tab to manage the current enhanced conversion activation state

![Settings Panel](https://github.com/woocommerce/google-listings-and-ads/assets/801097/f649a3e1-5018-4c6e-a8f9-151e5a7b1a91)

The behavior when this is enabled should follow the same ToS logic described in R2.1

- [x] Add panel in Google Listings & Ads Settings Tab that shows the current enhanced conversion activation state
```[tasklist]
### Updated Requirements
- [ ] Update Enhanced Conversions onboarding flow #2364
```

**Comment by joemcgill** [comment]
The UX for this feature has been updated. New details are in #2364.

**Comment by joemcgill** [comment]
This will be superseded by #2454. Closing.
