### ISSUE TITLE
Followup - Enhancing the method for fetching Product Overview Stats

### ISSUE THREAD

**Issue by jorgemd24** [woocommerce/google-listings-and-ads#2250]
### Migration Project

Part of https://github.com/woocommerce/google-listings-and-ads/issues/2146

Follow up of https://github.com/woocommerce/google-listings-and-ads/pull/2229

In PR https://github.com/woocommerce/google-listings-and-ads/pull/2229, we shifted the calculation from the product statistics to a background job. This opens up more options for enhancing performance when fetching statuses from the MC. Here's a list of potential tasks that could be implemented or explored to improve overall performance. Also it includes some pending tasks due to the changes made in this PR. 

#### Tasks

- [x] Schedule multiple jobs to fetch the product statistics using the page token. See https://github.com/woocommerce/google-listings-and-ads/pull/2229#discussion_r1479851013 
- [x] Explore checking the AS queue to determine if there are too many pending jobs. If so, attempt to execute the calculation without a job.
- [x] Increase MC status transient time. 
- [x] Explore to change WP_Post objects and bulk meta updates to WC_Product objects/CRUD classes. See https://github.com/woocommerce/google-listings-and-ads/pull/2229#pullrequestreview-1865229495
- [ ] Update the documentation regarding "Not Synced" to reflect the adjustments made in the calculation of unsynchronized products. See: https://github.com/woocommerce/google-listings-and-ads/pull/2229#discussion_r1482697054
- [x] Fix Issue with intermediate parents status.
- [x] Return error message if the `UpdateMerchantProductStatuses` job fails.
- [x] Add the UI to retry the `UpdateMerchantProductStatuses` job in case of failure.
- [x] Refactor issues
- [x] Delete stale postmeta for `mc_status` key
