### ISSUE TITLE
Conversion and remarketing tag implementation

### ISSUE THREAD

**Issue by findingsimple** [woocommerce/google-listings-and-ads#23]
**Description**

* Generate Google Ads conversion action and adds gTag to the merchant's website
* Generate remarketing tag and adds gTag to the merchant's website

**Technical**

* [Adapting an existing gtag integration](https://support.google.com/google-ads/answer/7548399?hl=en-AU#adapt_gtag) - if we detect the Woo GA plugin is installed

**Event tracking:**

* [WooCommerce Google Analytics Integration](https://github.com/woocommerce/woocommerce-google-analytics-integration)

**Status**
- [x] Insert Global Site Tag snippet on merchant's website
    - [x] Use woocommerce/woocommerce-google-analytics-integration when active
- [x] Ads conversion action
    - [x] Create default `WEBSITE` action during ads account setup process
    - [x] Retrieve Conversion ID and Conversion Label from created action and store them locally
    - [x] Inject Conversion ID into Global Site Tag 
    - [x] Add conversion event snippet (with Conversion ID and Label) to order confirmation page
- [x] Remarketing
    - [x] Inject Conversion ID into Global Site Tag 
    - Moved to #347 ~Add remarketing event snippet to all products (?)~
        > ~The event snippet tracks different actions and parameters. Install this snippet **on the pages where you want to track remarketing events**.~
