### ISSUE TITLE
Plugin Scaffolding

### ISSUE THREAD

**Issue by findingsimple** [woocommerce/google-listings-and-ads#24]
To get things started here are some thoughts (completely off the top of my head) about what we will possibly need (or at least need to consider)

We'll be supporting PHP 7+ (that means 8 etc.)

- [x] Tests
  - [x] PHP Unit
  - [x] E2E (Based off Woo core - there is some prior art in AutomateWoo)
  - [x] JS tests
- [x] Linting
  - [x] WP coding standards (at least a subset of)
  - [x] Editor config file
  - [x] stylehint file
  - [x] jshint file
- [x] CI / Travis (~potentially look at actions~ actions aren't available in private repos on legacy accounts)
  * https://github.com/woocommerce/woocommerce/actions
  * https://github.com/woocommerce/woocommerce-gutenberg-products-block/actions
  * https://make.wordpress.org/core/2020/10/15/introducing-github-actions-for-automated-testing/
- [x] Initial Packages / Dependencies
  - [x] Tracks (we'll need to use both Woo core php based tracks logging + javascript using the [woocommerce/tracks](https://www.npmjs.com/package/@woocommerce/tracks) package)
  - [ ] ~Action Scheduler (we'll use the version bundled with core)~
  - [ ] ~Integrate with WooCommerce Logging~
  - [x] [Jetpack Connection Module](https://github.com/Automattic/jetpack-connection)
  - [x] [Google PHP Client Library](https://github.com/googleapis/google-api-php-client)
  - [x] [Google Ads PHP Client Library](https://github.com/googleads/google-ads-php) 
- [ ] ~Automated Translations - there is some prior art in AutomateWoo - note we may not be able to fully set this up initially but it should be ready to go.~
- [ ] ~WooRelease - won't be needed straight away but definitely needs to be piped in.~
- [x] Integrate with WooCommerce Admin
  * https://developer.woocommerce.com/2020/10/16/using-the-admin-notes-inbox-in-woocommerce/ (use wp-env as an easy setup development environment? 🤔 
  * https://developer.woocommerce.com/2020/09/11/building-a-javascript-driven-ui-for-automatewoo-part-1-setting-up-wordpress-scripts-and-webpack/
- [x] Github Issue + PR Templates => #31

Notes
* I'd like to try and be consistent with tools/tech/setup used thoughout Woo - webpack, composer, wp-scripts etc.
* Lets not over-engineer
