### ISSUE TITLE
Onboarding: Consolidation of account creation/connection cards

### ISSUE THREAD

**Issue by joemcgill** [woocommerce/google-listings-and-ads#2509]
As part of the Onboarding Improvements project (#2458), we want to consolidate the functionality and UX from three separate cards that are responsible for connecting to a Google account, a Google Ads account, and a Google Merchant Center account, into a new single flow.

**Current UI:**
<img width="1056" alt="image" src="https://github.com/user-attachments/assets/47cb670c-f3e9-485b-ac9f-9297dc17d9a5">

## Proposed flow
There are 4 possible scenarios to account for:

<img width="474" alt="image" src="https://github.com/user-attachments/assets/060abe8d-19fe-47a5-a9fe-3011dfc747bc">

1. Merchant doesn’t have Merchant Center accounts nor Google Ads accounts. 
2. Merchant has one or more Merchant Center account but not an Google Ads account.
3. Merchant has one or more Merchant Center and Google Ads accounts.
4. Merchant doesn’t have Merchant Center accounts but has one or more Google Ads accounts.

## Design Overview

Design mocks are being iterated on in [this Figma file](https://www.figma.com/design/fqR0EHi63lWahRcVTKCcba/Google-Listings-%26-Ads-v2.x?node-id=7176-108902&t=eFMkAn0y2V4OQmPR-0).

The new combined Google account connection card will begin by asking the user to accept terms & conditions for Google MC and Google Ads before starting the connection process.

![Image](https://github.com/user-attachments/assets/a36dde89-7e72-45dc-a73a-22385731475a)

Once checked, the Connect button will be enabled, allowing the user to begin by setting up their Google account and enter the current OAuth flow.

![Image](https://github.com/user-attachments/assets/8c93fe24-8099-4b61-934e-00aaec600f17)

Once all of the necessary permissions are granted, the Google combo card will see if any Ads or MC accounts already exist for that Google account. 

If no accounts exist, they will automatically be created to start to onboarding process.

![Image](https://github.com/user-attachments/assets/5fb50126-ff4a-4e6c-826a-b378d7ac1654)

If the Google account already has existing Ads or MC accounts, a new combo view will allow the user to select which accounts to connect, along with some recommendations based on info we can infer from the account status. See an example of choosing an MC account in the following screenshot.

![Image](https://github.com/user-attachments/assets/c4457836-4f68-4158-8ace-5e3db2f688f9)

## Technical Design
This feature will be worked on over multiple sub-tasks. Once #2566 issue is done, Each task should be branched off of [feature/2509-consolidate-google-account-cards](https://github.com/woocommerce/google-listings-and-ads/tree/feature/2509-consolidate-google-account-cards) and PRs should be opened against the same feature branch.

The task list below is in progress.

```[tasklist]
### Tasks
- [ ] https://github.com/woocommerce/google-listings-and-ads/issues/2565
- [ ] https://github.com/woocommerce/google-listings-and-ads/issues/2566
- [ ] https://github.com/woocommerce/google-listings-and-ads/issues/2567
- [ ] https://github.com/woocommerce/google-listings-and-ads/issues/2582
- [ ] https://github.com/woocommerce/google-listings-and-ads/issues/2592
- [ ] https://github.com/woocommerce/google-listings-and-ads/issues/2593
- [ ] https://github.com/woocommerce/google-listings-and-ads/issues/2596
- [ ] https://github.com/woocommerce/google-listings-and-ads/issues/2597
- [ ] https://github.com/woocommerce/google-listings-and-ads/issues/2603
- [ ] https://github.com/woocommerce/google-listings-and-ads/issues/2604
- [ ] https://github.com/woocommerce/google-listings-and-ads/issues/2605
- [ ] https://github.com/woocommerce/google-listings-and-ads/issues/2606
- [ ] https://github.com/woocommerce/google-listings-and-ads/issues/2607
- [ ] https://github.com/woocommerce/google-listings-and-ads/issues/2602
- [ ] Review classname of section footer `gla-google-mc-account-section`
- [ ] https://github.com/woocommerce/google-listings-and-ads/issues/2674
```

**Comment by joemcgill** [comment]
Assigning this to @michaeleleder to work on some design mocks for these flows. Once they're ready we can create sub-tasks for any actionable work needed to make these changes.

**Comment by joemcgill** [comment]
Added a follow-up item to the task list to review the classname of the footer section of the account creation page, per [this conversation](https://github.com/woocommerce/google-listings-and-ads/pull/2585#discussion_r1749729768).

**Comment by mikkamp** [comment]
Closing this as completed since it was part of the [2.9 release](https://github.com/woocommerce/google-listings-and-ads/releases/tag/2.9.0).
