### ISSUE TITLE
Check tracking

### ISSUE THREAD

**Issue by findingsimple** [woocommerce/google-listings-and-ads#279]
The backlog of tracking related tasks that we need to circle back to and handle separately before launch (we didn't want to block initial feature development.

* [x] [Track successful and unsuccessful verification attempts](https://github.com/woocommerce/google-listings-and-ads/issues/9)
* [ ] [Track successful and unsuccessful claims (collisions etc.)](https://github.com/woocommerce/google-listings-and-ads/issues/10)
* [ ] Jetpack Account Connects and Disconnects
* [ ] Google Account Connects and Disconnects
* [ ] [Google Ads Onboarding](https://github.com/woocommerce/google-listings-and-ads/issues/80) 

https://github.com/woocommerce/google-listings-and-ads/issues/406

Settings

* [ ] [Tax Settings](https://github.com/woocommerce/google-listings-and-ads/issues/11)
* [ ] [Shipping Settings](https://github.com/woocommerce/google-listings-and-ads/issues/12)
* [ ] [Target Audience](https://github.com/woocommerce/google-listings-and-ads/issues/17)

Remove

* [x] [Events Loaded Demo](https://github.com/woocommerce/google-listings-and-ads/blob/87e88508384a2cb1b3c539e380bb3f24797b1396/src/Tracking/Events/Loaded.php)

---

PHP - Search for `record_event`
JS - Search for `recordEvent`
