### ISSUE TITLE
Discovery: Promote paid listings after free listings are configured

### ISSUE THREAD

**Issue by findingsimple** [woocommerce/google-listings-and-ads#7]
**User story:**

As a merchant
I want to know about new marketing opportunities/ways I can enhance my marketing
So that I can reach more customers

**Description:**

Once a Merchant successfully onboards to the Merchant Center free listings. Promote the paid listing functionality.

**Acceptance criteria:**

* [x] Inbox notification is triggered to merchants after free listing setup is complete (but before paid listings are setup).
* [x] Paid listings are promoted on the overview page before they are setup
* [x] Clicking the call to action will prompt the user to _setup ads account_

One the overview/dashboard page the following should be displayed linking to the Ads initial Ads onboarding flow.

![Screen Shot 2021-01-26 at 4 20 33 pm](https://user-images.githubusercontent.com/355014/105805779-acc13680-5ff2-11eb-8a07-060e4fd93ea6.png)

**Figma link**

https://www.figma.com/file/jZUpa8eTrnrK1Lwt2ry7zk/Native-Google-Integration?node-id=2123%3A59239

**Dependencies**

* Overview page
* Set up ads account / Ads onboarding flow

**Event tracking:**

* [x] Inbox notification tracking should already be setup - will need to confirm and document
* [x] Tracks event should be triggered when paid lists promotion is clicked
