### ISSUE TITLE
Merchant Center Account

### ISSUE THREAD

**Issue by findingsimple** [woocommerce/google-listings-and-ads#8]
**User story:**

As a merchant
I want to connect my store to the Merchant Center
So that I can easily enable my Google free listings

**Description:**

In order to make use of Google's free listing, Merchants must connect (or create first) their Merchant Center account.

If they don't have an existing account

![Screen Shot 2020-11-03 at 4 31 48 pm](https://user-images.githubusercontent.com/355014/97953977-16fe7c80-1df2-11eb-906c-15073de22766.png)

If they do have an existing account

![Screen Shot 2020-11-03 at 4 32 46 pm](https://user-images.githubusercontent.com/355014/97954023-3a292c00-1df2-11eb-8f69-72ed2cc9145a.png)

A snackbar notice will be displayed to provide feedback to the merchant on success/failure,

**Technical:**

* WordPress.com account and Google account must be connected first.
* Button component
* Snackbar notice component
* We won't give merchants the option to enter an account name, we'll programmatically set it (format TBC)
* The merchant’s Google Account must be added as an administrative user of the Merchant Center account created for them (This is a solution requirement)
* For ToS link the merchant to https://support.google.com/merchants/answer/160173 
* Store the Terms of Service acceptance response from the merchant with a timestamp when the Terms of Service were accepted.
* Refer to WooCommerce Shopping Integration Overview for example flow...

<img width="1192" alt="Screen Shot 2020-11-12 at 6 25 05 pm" src="https://user-images.githubusercontent.com/355014/98911441-83752c00-2514-11eb-90c6-eb49d0a29e58.png">

**Acceptance criteria:**

* [x] Merchant must accept Google’s ToS so that they can use Google's Services **(new accounts only)**
* [x] Acceptance of ToS are stored for future reference with a timestamp indicating when the terms were accepted.
* [x] For ToS link Merchant to https://support.google.com/merchants/answer/160173
* [x] Merchant can choose to connect to an existing Merchant Center Account
* [x] Merchant can create a new Merchant Center Account
* [x] The merchant’s Google Account must be added as an administrative user of the Merchant Center account created for them.
* [x] Merchant can choose to disconnect their account
* [x] Button color updates to reflect admin profile color scheme
* [ ] Tracks event/s fired
* [x] Translatable text
* [ ] Snackbar notice displayed

**Dependencies**

* [Full screen set up screen/page](https://github.com/woocommerce/google-for-woocommerce/issues/44)
* [Google Account Connection](https://github.com/woocommerce/google-for-woocommerce/issues/2)
* [WordPress.com Connection](https://github.com/woocommerce/google-for-woocommerce/issues/1)

**Event tracking:** 

* [ ] Track whether an existing account is used or whether one is created
* [ ] Track disconnects
* [ ] Track acceptance of ToS
