### ISSUE TITLE
Site Verification

### ISSUE THREAD

**Issue by findingsimple** [woocommerce/google-listings-and-ads#9]
**User story:**

As a merchant
I want to verify my site with Google
So that I can prove that I own the property.

**Description:**

Merchants must prove that they own the property/site they are trying to connect to the Merchant Center.

* [Four verification methods](https://developers.google.com/site-verification/v1/getting_started#site-verification-methods) can be used in conjunction with Site Verification API - inserting meta is the simplest to implement for us
* Sites can be verified multiple times - so shouldn't be any issues adding the meta to a site that already has it (confirmed with Google team)
* Verification is done with the Site Verification API

**Technical:**

* Requires Merchant Center Account to be connected
* Refer to WooCommerce Shopping Integration Overview for example flow

**Acceptance criteria:**

* [x] Solution Requirement - Add Google User as admin to MC Account
* [x] Automatically insert meta in website header

**Dependencies**

* [Full screen set up screen/page](https://github.com/woocommerce/google-for-woocommerce/issues/44)
* [Merchant Center Account](https://github.com/woocommerce/google-for-woocommerce/issues/8)

**Event tracking:**

* [x] Track successful and unsuccessful verification attempts
